language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-marionette-app' ]; then cd .. && eval "mv $currentfolder generator-marionette-app" && cd generator-marionette-app; fi
